---

user: ubuntu

allow_bootnode_ssh: true
allow_bootnode_p2p: true
allow_bootnode_rpc: false

username: "bootnode"
users:
  - name: "{{ username }}"
home: "/home/{{ username }}"

bootnode_archive: "off"
bootnode_orchestrator: "off"