---

user: ubuntu

username: "poa"
users:
  - name: "{{ username }}"

allow_validator_ssh: true
allow_validator_p2p: true
validator_archive: "off"

GENESIS_NETWORK_NAME: "PoA"
NODE_PWD: "node.pwd" # don't change this one
MINING_KEYFILE: ""
MINING_KEYPASS: ""
MINING_ADDRESS: "0xdd0bb0e2a1594240fed0c2f2c17c1e9ab4f87126"
SCRIPTS_VALIDATOR_BRANCH: "mainnet"
MAIN_REPO_FETCH: "poanetwork"
BLK_GAS_LIMIT: "6700000"
