---
- name: Copy spec.json and bootnodes.txt to remote machine
  copy: src={{ spec_json }} dest={{ home }}/ mode=0644 group={{ username }} owner={{ username }}
  when: spec_json != ""
  with_items:
    - "{{ spec_json }}"
    - "{{ bootnodes_txt }}"

- name: Download spec.json and bootnodes.txt
  get_url: url={{ item }} dest={{ home }}/ mode=0644 group={{ username }} owner={{ username }}
  with_items:
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/{{ GENESIS_BRANCH }}/spec.json"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/{{ GENESIS_BRANCH }}/bootnodes.txt"
  when: spec_json == ""