dependencies:
  - { role: usermanager }
  - { role: preconf }
  - { role: nodejs }
  - { role: poa-logrotate }
  - { role: poa-parity }
  - { role: poa-pm2 }
  - { role: poa-netstats }
  - { role: poa-orchestrator, when: "(bootnode_orchestrator or 'off') == 'on'" }
  - { role: nginx }
  - { role: debug-tools, when: "install_debug_tools == 'yes'" }
