---
- name: Add ssh keys for "{{ outer_item.name }}"
  authorized_key: "user={{ outer_item.name }} key='{{ lookup('file', item) }}' state=present exclusive=yes"
  with_first_found:
    - files:
      - "ssh_{{ env }}_{{ outer_item.name }}_{{ inventory_hostname }}.pub"
      - "ssh_{{ env }}_{{ outer_item.name }}.pub"
      - "ssh_{{ env }}.pub"
      - "ssh_{{ outer_item.name }}.pub"
      - "{{ key_name.split('/')[:-1] }}"
    - paths:
       - ../../../files
       - ../../../../.
       - "{{ dirname(keyname) }}"
